### ISSUE TITLE
Can't resolve 'create-react-class'

### ISSUE THREAD

**Issue by jcristol** [zillow/react-slider#127]
Running a fresh install of react-slider. Trying to simply import `ReactSlider`. I get a node modules error that says `Module not found: Can't resolve 'create-react-class' in '/Users/JoshuaCristol/pspace/budgetbois/budgetapp/frontend-budgetapp/app/node_modules/react-slider'`. I suspect this is something to do with my version of react or because I am using create react app. I am new to react so I could be doing something boneheaded just let me know.

-jcris

**Comment by larrycustodio** [comment]
Try adding the `create-react-class` library in your dependencies, and then run your build script

`npm install create-react-class`

https://github.com/mpowaga/react-slider/issues/120

**Comment by IoanaCretiu** [comment]
I have the same issue. Adding create-react-class does not resolve the problem.

**Comment by d07RiV** [comment]
Why isn't it in package dependencies? Adding it to my project dependencies is wrong, because if I choose to switch to a different slider library, I will have unnecessary dependencies left in my config.

**Comment by stonebk** [comment]
Fixed with #147

**Comment by olliecurtis** [comment]
Hey @stonebk 👋 

I am receiving this issue when compling and running the library, from doing some digging it seems you are referencing `create-react-class` in the `index.html` file:

`<script src="node_modules/create-react-class/create-react-class.js"></script>`

Can we add it as a dependency to this library? 

I see it was added in this PR https://github.com/zillow/react-slider/pull/104 

Then removed in this PR here: https://github.com/zillow/react-slider/pull/147

Can I check why it was removed here?

**Comment by stonebk** [comment]
Oops, that index.html file is no longer valid and should be removed! You should run the library with `npm run start` now.

**Comment by stonebk** [comment]
@ojcurtis, ok, all cleaned up now:
https://github.com/zillow/react-slider/commit/21265f72904450169c46bccb06cb540a2aa634d0

**Comment by olliecurtis** [comment]
@stonebk - Is is possible to create a release for this fix? As I am still getting the error when compling my library and using `react-slider` as a dep

```
./node_modules/react-slider/react-slider.js
Module not found: Error: Can't resolve 'create-react-class' in '/Users/user/docs/node_modules/react-slider'
```

**Comment by stonebk** [comment]
@ojcurtis Version `1.0.0` and greater does not have any dependency on `create-react-class`. What version are you on?

`npm ls react-slider`

**Comment by olliecurtis** [comment]
@stonebk thanks for the response, I see I just need to upgrade my dependency 😄 current version `react-slider@0.11.2` so will explain it. Cheers for the confirmation should've checked that first
